// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderBookingFormApp.Data;

#nullable disable

namespace OrderBookingFormApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241218070212_AddedBookingInfoAPiRespTable")]
    partial class AddedBookingInfoAPiRespTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OrderBookingFormApp.Models.BookingInfoAPIResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateTimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsBookingSMSSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResponseMsg")
                        .HasColumnType("longtext");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("bookinginfo_api_response");
                });

            modelBuilder.Entity("OrderBookingFormApp.Models.ConfirmSalesBooking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AadharBackImg_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("AadharFrontImg_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("AadharUploadDoc_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Accessories")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Age")
                        .HasColumnType("longtext");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("BookingDate")
                        .HasColumnType("longtext");

                    b.Property<string>("CESS1Percent")
                        .HasColumnType("longtext");

                    b.Property<string>("CGST14Percent")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ConfirmedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CorporateName")
                        .HasColumnType("longtext");

                    b.Property<long?>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhoto_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerSignature_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerType")
                        .HasColumnType("longtext");

                    b.Property<string>("DOA")
                        .HasColumnType("longtext");

                    b.Property<string>("DOB")
                        .HasColumnType("longtext");

                    b.Property<string>("Discount")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("DmsObfNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EwOptional")
                        .HasColumnType("longtext");

                    b.Property<string>("ExShowroomPrice")
                        .HasColumnType("longtext");

                    b.Property<string>("Exchangestatus")
                        .HasColumnType("longtext");

                    b.Property<string>("ExistingCarModel")
                        .HasColumnType("longtext");

                    b.Property<string>("Expecteddate")
                        .HasColumnType("longtext");

                    b.Property<string>("FatherOrHusbandName")
                        .HasColumnType("longtext");

                    b.Property<string>("Finance")
                        .HasColumnType("longtext");

                    b.Property<string>("InsurancePrice")
                        .HasColumnType("longtext");

                    b.Property<string>("MSILListedCorporate")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("ObfPDF_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("OnRoadPrice")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherContactNo")
                        .HasColumnType("longtext");

                    b.Property<string>("OthersDescribe")
                        .HasColumnType("longtext");

                    b.Property<string>("OthersIfAny")
                        .HasColumnType("longtext");

                    b.Property<string>("PanCardImg_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("PanCardNo")
                        .HasColumnType("longtext");

                    b.Property<string>("PancardUploadDoc_FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumbers")
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Profession")
                        .HasColumnType("longtext");

                    b.Property<string>("Promiseddate")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationCharges")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("longtext");

                    b.Property<string>("SGST14Percent")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceOfEnquiry")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Taluk")
                        .HasColumnType("longtext");

                    b.Property<string>("TempRegCharges")
                        .HasColumnType("longtext");

                    b.Property<string>("TentativeWaitPeriod")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEnteredName")
                        .HasColumnType("longtext");

                    b.Property<string>("Variant")
                        .HasColumnType("longtext");

                    b.Property<long?>("VehicleID")
                        .HasColumnType("bigint");

                    b.Property<string>("Village")
                        .HasColumnType("longtext");

                    b.Property<bool>("isSubmit")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("confirm_salesbooking");
                });

            modelBuilder.Entity("OrderBookingFormApp.Models.EnquiryAPIResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateTimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnquiryDataPosted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResponseMsg")
                        .HasColumnType("longtext");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("enquiry_api_response");
                });

            modelBuilder.Entity("OrderBookingFormApp.Models.GeneratedOTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("OTP")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("generated_otp");
                });

            modelBuilder.Entity("OrderBookingFormApp.Models.SMSInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InteractionDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<long?>("MobileNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("MsgStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseFromGateway")
                        .HasColumnType("longtext");

                    b.Property<string>("SmsType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sms_interaction");
                });

            modelBuilder.Entity("OrderBookingFormApp.Models.SMSTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DealerName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SMSApi")
                        .HasColumnType("longtext");

                    b.Property<string>("SMSRoute")
                        .HasColumnType("longtext");

                    b.Property<string>("SMSSenderHeaderId")
                        .HasColumnType("longtext");

                    b.Property<string>("SMSTemplate")
                        .HasColumnType("longtext");

                    b.Property<string>("SMSTemplateId")
                        .HasColumnType("longtext");

                    b.Property<string>("SMSTemplateName")
                        .HasColumnType("longtext");

                    b.Property<string>("SMSType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sms_templates");
                });

            modelBuilder.Entity("OrderBookingFormApp.Models.SalesBookedData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Accessories")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Age")
                        .HasColumnType("longtext");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("BookingDate")
                        .HasColumnType("longtext");

                    b.Property<string>("CESS1Percent")
                        .HasColumnType("longtext");

                    b.Property<string>("CGST14Percent")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("CorporateName")
                        .HasColumnType("longtext");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerType")
                        .HasColumnType("longtext");

                    b.Property<string>("DOA")
                        .HasColumnType("longtext");

                    b.Property<string>("DOB")
                        .HasColumnType("longtext");

                    b.Property<string>("Discount")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("DmsObfNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EwOptional")
                        .HasColumnType("longtext");

                    b.Property<string>("ExShowroomPrice")
                        .HasColumnType("longtext");

                    b.Property<string>("Exchangestatus")
                        .HasColumnType("longtext");

                    b.Property<string>("ExistingCarModel")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpectedDateForEnquiryApi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Expecteddate")
                        .HasColumnType("longtext");

                    b.Property<string>("FatherOrHusbandName")
                        .HasColumnType("longtext");

                    b.Property<string>("Finance")
                        .HasColumnType("longtext");

                    b.Property<string>("InsurancePrice")
                        .HasColumnType("longtext");

                    b.Property<string>("MSILListedCorporate")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("OnRoadPrice")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherContactNo")
                        .HasColumnType("longtext");

                    b.Property<string>("OthersDescribe")
                        .HasColumnType("longtext");

                    b.Property<string>("OthersIfAny")
                        .HasColumnType("longtext");

                    b.Property<string>("PanCardNo")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumbers")
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Profession")
                        .HasColumnType("longtext");

                    b.Property<string>("Promiseddate")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationCharges")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("longtext");

                    b.Property<string>("SGST14Percent")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceOfEnquiry")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Taluk")
                        .HasColumnType("longtext");

                    b.Property<string>("TempRegCharges")
                        .HasColumnType("longtext");

                    b.Property<string>("TentativeWaitPeriod")
                        .HasColumnType("longtext");

                    b.Property<string>("Variant")
                        .HasColumnType("longtext");

                    b.Property<long>("VehicleID")
                        .HasColumnType("bigint");

                    b.Property<string>("Village")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("salesbooked_data");
                });
#pragma warning restore 612, 618
        }
    }
}
